name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install --upgrade pylint
        pip install pytest
        pip install --upgrade pytest
        pip install twilio  # Install twilio library
    - name: Analysing the code with pylint
      run: |
        pylint $(find . -name '*.py')
    - name: Run tests with pytest
      run: |
        pytest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Streamlit
      run: |
        python -m pip install streamlit
    - name: Deploy to Streamlit Cloud
      run: |
        streamlit run otp_app.py --server.headless true
